


def main():


    sql1 = "UPDATE PREVENT2 SET NU_PREVENT= '2',NATURE=NULL,TITRE= 'PM2 TITLE',PERIODE= '1',DATEDEB= '20200827',HEUREDEB= '0800',DATEFIN=NULL,HEUREFIN=NULL,DATEORIG=NULL,DATESAISI=NULL,COMPORIG=0,COMPSAISI=0,PERIODELA=60,PERIOCOMP=0,INT_EXT= '1',INT_CM= 'DI',TECHN=NULL,CODE_FOUR=NULL,NOM_FOUR=NULL,TECHN_FOUR=NULL,N_CONTRAT=NULL,OBSERV=NULL,TYPE_PREV=NULL,TYPE_NOM= '1',STATUE= '1',IS_CALLER_NOTIFIED=1,IS_TECHN_NOTIFIED=1,IS_SERVICE_PROVIDER_NOTIFIED=0,DATE_REFOR=NULL,INSERT_DATE= '20200827115008193',UPDATE_DATE= '20210604162158640',TOLERANCE=0,ESTIMATED_DURATION= '0200',PERIODICITY_OCCURRENCE=60,PERIODICITY_DMY=1,RI_SUIVI_CM=NULL,RI_SUIVI_TECHN=NULL,TOOLS=NULL,AUTO_CONVERT_WO=1,AUTO_PRINT_OUT=1,DOCS_PRINT_OUT=1,FILLER1=NULL,FILLER2=NULL,FILLER3=NULL,FILLER4=NULL,FILLER5=NULL,TOLERANCE_DMY=1,ALERTE=0,ALERTE_DMY=1,V_FONC=NULL,PM_CADRE= '1',TYPE_REFOR=NULL,TOLERANCE_DAYS= '0',AUTO_CONVERT_WO_DAYS= '0',ID_USERTABLE1_PM= '0',ID_USERTABLE2_PM= '0',ID_USERTABLE3_PM= '0',ALREADY_CONVERTED=0,WO_STATUS_CONVERSION= '1',CALL_STATUS= '1',IS_EXCLUDE_WEEKEND=0,PLANNED_OCCURRENCE=0,PLANNED_OCCURRENCE_DMY=1,DATE_OCCURRENCE_END_TO= '20210806',IS_NEXT_PM_AFTER_WO=0,AUTO_CONVERSION_PROFILE=NULL WHERE  NU_PREVENT = '2'"

    sql2 = "UPDATE PARANUM SET NUMERO = 44 WHERE NOMTAB = 'PREV_EQP'"


if __name__ == '__main__':
    main()

